management:
    endpoint:
        health:
            enabled: true
            show-details: always
        info:
            enabled: true
        metrics:
            enabled: true
        shutdown:
            enabled: true
    endpoints:
        web:
            exposure:
                include: metrics,health,info
spring:
    datasource:
        url: jdbc:h2:file:./h2db
        driverClassName: org.h2.Driver
        username: sa
        password: password
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
logging:
    level:
        org:
            springframework:
                boot:
                    autoconfigure:
                        logging: ERROR
